import { readFileSync, writeFileSync } from 'node:fs';

import { buildMaze, parseJm2Locs, solveRoute, MAZE_SHRINE, MAZE_SPAWNS, edgeKey, WALL_ID, DOOR_DIRS } from '../src/bot/api/maze/mazeGraph.js';

function parseArgs(): { map: string; out: string } {
    const args = process.argv.slice(2);
    let map = new URL('../test/api/maze/fixtures/m45_71.jm2', import.meta.url).pathname;
    let out = 'src/bot/api/maze/mazeLayout.ts';
    for (let i = 0; i < args.length; i++) {
        if (args[i] === '--map') { map = args[++i]; }
        else if (args[i] === '--out') { out = args[++i]; }
        else { console.error(`unknown argument: ${args[i]}`); process.exit(2); }
    }
    return { map, out };
}

const { map, out } = parseArgs();
const locs = parseJm2Locs(readFileSync(map, 'utf8'));
const g = buildMaze(locs);
// Rendered for eyeballing only. The shipped artefact is the layout, not these
// routes: the spawn tile varies per event, so routes are solved at runtime.
const routes = MAZE_SPAWNS.map(spawn => ({ spawn, doors: solveRoute(g, spawn) }));

function render(spawn: { x: number; z: number }, doors: { x: number; z: number }[]): string {
    const onRoute = new Set(doors.map(d => `${d.x},${d.z}`));
    const rows: string[] = [];
    for (let z = g.maxz; z >= g.minz; z--) {
        let row = '';
        for (let x = g.minx; x <= g.maxx; x++) {
            if (x === MAZE_SHRINE.x && z === MAZE_SHRINE.z) { row += 'X'; }
            else if (x === spawn.x && z === spawn.z) { row += 'S'; }
            else if (onRoute.has(`${x},${z}`)) { row += 'D'; }
            else if (g.wallEdge.has(edgeKey(x, z, x + 1, z)) || g.wallEdge.has(edgeKey(x, z, x, z + 1))) { row += '#'; }
            else { row += '.'; }
        }
        rows.push(row);
    }
    return rows.join('\n');
}

for (const r of routes) {
    console.log(`\n=== spawn (${r.spawn.x},${r.spawn.z}) — ${r.doors.length} doors ===`);
    console.log(render(r.spawn, r.doors));
}

// Only walls and doors shape the graph; everything else in the map square is decor.
const relevant = locs.filter(l => l.id === WALL_ID || l.id in DOOR_DIRS);
const packed = relevant.flatMap(l => [l.lx, l.lz, l.id, l.shape, l.angle]);
const rows: string[] = [];
for (let i = 0; i < packed.length; i += 50) {
    rows.push('    ' + packed.slice(i, i + 50).join(','));
}
const file = `// GENERATED by tools/maze-derive.ts — do not edit by hand.
// Regenerate: bun tools/maze-derive.ts
//
// The maze map square is static game data; only the spawn tile varies per event,
// so the layout ships and routes are solved at runtime for wherever the player
// actually landed. Packed as flat [lx, lz, id, shape, angle] quintuples.

export const MAZE_LAYOUT_STRIDE = 5;

export const MAZE_LAYOUT: number[] = [
${rows.join(',\n')}
];
`;
writeFileSync(out, file);
console.log(`\nwrote ${out}`);
